name: wordsy
favicon: null
layout_spectrum: 0.24047499103471637
typography_spectrum: 0.6749442087020725
title: Inspiration and Motivation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.10863742884248495
purpose: []
