name: wordsy
favicon: null
layout_spectrum: 0.98827
typography_spectrum: 0.50271
title: Inspiration and Motivation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#476b97'
    - '#7898b1'
    - '#1e2432'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
